# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
_py-xgboost-mutex=2.0=cpu_0
_tflow_select=2.1.0=gpu
absl-py=0.9.0=py37_0
anyconfig=0.9.10=py_0
appdirs=1.4.3=py37h28b3542_0
arrow=0.15.5=pypi_0
arrow-cpp=0.11.1=py37h5c3f529_1
asn1crypto=1.3.0=py37_0
astor=0.8.0=py37_0
attrs=19.3.0=py_0
azure-common=1.1.25=pypi_0
azure-storage-blob=1.5.0=pypi_0
azure-storage-common=1.4.2=pypi_0
azure-storage-file=1.4.0=pypi_0
azure-storage-queue=1.4.0=pypi_0
backcall=0.1.0=py37_0
binaryornot=0.4.4=pypi_0
black=19.10b0=py_0
blas=1.0=mkl
bleach=3.1.0=py37_0
blinker=1.4=py37_0
blosc=1.16.3=hd408876_0
bokeh=2.0.0=py37_0
boto3=1.12.26=pypi_0
botocore=1.15.26=pypi_0
bzip2=1.0.8=h7b6447c_0
c-ares=1.15.0=h7b6447c_1001
ca-certificates=2020.1.1=0
cachetools=3.1.1=py_0
certifi=2019.11.28=py37_0
cffi=1.14.0=py37h2e261b9_0
chardet=3.0.4=py37_1003
click=7.1.1=py_0
cloudpickle=1.1.1=py_0
colorcet=2.0.2=py_0
cookiecutter=1.7.0=pypi_0
cryptography=2.8=py37h1ba5d50_0
cudatoolkit=10.1.243=h6bb024c_0
cudnn=7.6.5=cuda10.1_0
cupti=10.1.168=0
cvxopt=1.2.0=py37hfa32c7d_0
cvxpy=1.0.27=py37he1b5a44_0
cvxpy-base=1.0.27=py37he1b5a44_0
cycler=0.10.0=py37_0
cython=0.29.15=py37he6710b0_0
dbus=1.13.12=h746ee38_0
decorator=4.4.2=py_0
defusedxml=0.6.0=py_0
dill=0.3.1.1=py37_0
docutils=0.15.2=pypi_0
ecos=2.0.7.post1=py37hc1659b7_1
entrypoints=0.3=py37_0
expat=2.2.6=he6710b0_0
fastcache=1.1.0=py37h8f50634_1
flake8=3.7.9=py37_0
fontconfig=2.13.0=h9420a91_0
freetype=2.9.1=h8a8886c_1
fsspec=0.6.2=py_0
future=0.18.2=py37hc8dfbb8_1
gast=0.2.2=py37_0
gflags=2.2.2=he6710b0_0
glib=2.63.1=h5a9c865_0
glog=0.3.5=hf484d3e_1
glpk=4.65=h3ceedfd_2
gmp=6.1.2=h6c8ec71_1
google-api-core=1.16.0=pypi_0
google-auth=1.11.2=py_0
google-auth-oauthlib=0.4.1=py_2
google-cloud-bigquery=1.24.0=pypi_0
google-cloud-core=1.3.0=pypi_0
google-pasta=0.1.8=py_0
google-resumable-media=0.5.0=pypi_0
googleapis-common-protos=1.51.0=pypi_0
grpcio=1.27.2=py37hf8bcb03_0
gsl=2.4=h14c3975_4
gst-plugins-base=1.14.0=hbbd80ab_1
gstreamer=1.14.0=hb453b48_1
h5py=2.10.0=py37h7918eee_0
hdf5=1.10.4=hb1b8bf9_0
holoviews=1.12.7=py_0
hvplot=0.5.2=py_1
icu=58.2=h9c2bf20_1
idna=2.9=py_1
importlib_metadata=1.5.0=py37_0
intel-openmp=2020.0=166
ipykernel=5.1.4=py37h39e3cac_0
ipython=7.13.0=py37h5ca1d4c_0
ipython_genutils=0.2.0=py37_0
jedi=0.16.0=py37_0
jinja2=2.11.1=py_0
jinja2-time=0.2.0=pypi_0
jmespath=0.9.4=py_0
joblib=0.14.1=py_0
jpeg=9b=h024ee3a_2
json5=0.9.2=py_0
jsonschema=3.2.0=py37_0
jupyter_client=6.0.0=py_0
jupyter_core=4.6.1=py37_0
jupyterlab=1.2.6=pyhf63ae98_0
jupyterlab_server=1.0.7=py_0
kedro=0.15.8=pypi_0
keras-applications=1.0.8=py_0
keras-preprocessing=1.1.0=py_1
kiwisolver=1.1.0=py37he6710b0_0
ld_impl_linux-64=2.33.1=h53a641e_7
libblas=3.8.0=15_mkl
libboost=1.67.0=h46d08c1_4
libedit=3.1.20181209=hc058e9b_0
libevent=2.1.8=h1ba5d50_0
libffi=3.2.1=hd88cf55_4
libgcc-ng=9.1.0=hdf63c60_0
libgfortran-ng=7.3.0=hdf63c60_0
liblapack=3.8.0=15_mkl
libpng=1.6.37=hbc83047_0
libprotobuf=3.11.4=hd408876_0
libsodium=1.0.16=h1bed415_0
libstdcxx-ng=9.1.0=hdf63c60_0
libtiff=4.1.0=h2733197_0
libuuid=1.0.3=h1bed415_2
libxcb=1.13=h1bed415_1
libxgboost=0.90=he6710b0_1
libxml2=2.9.9=hea5a465_1
lz4-c=1.8.1.2=h14c3975_0
lzo=2.10=h49e0be7_2
markdown=3.1.1=py37_0
markupsafe=1.1.1=py37h7b6447c_0
matplotlib=3.1.3=py37_0
matplotlib-base=3.1.3=py37hef1b27d_0
mccabe=0.6.1=py37_1
metis=5.1.0=hf484d3e_4
mistune=0.8.4=py37h7b6447c_0
mkl=2020.0=166
mkl-service=2.3.0=py37he904b0f_0
mkl_fft=1.0.15=py37ha843d7b_0
mkl_random=1.1.0=py37hd6b4f25_0
mock=4.0.1=py_0
multiprocess=0.70.9=py37h8f50634_1
mypy_extensions=0.4.3=py37_0
nbconvert=5.6.1=py37_0
nbformat=5.0.4=py_0
ncurses=6.2=he6710b0_0
notebook=6.0.3=py37_0
numexpr=2.7.1=py37h423224d_0
numpy=1.18.1=py37h4f9e942_0
numpy-base=1.18.1=py37hde5b4d6_1
oauthlib=3.1.0=py_0
olefile=0.46=py37_0
openssl=1.1.1e=h7b6447c_0
opt_einsum=3.1.0=py_0
osqp=0.5.0=pypi_0
packaging=20.3=py_0
pandas=0.25.3=pypi_0
pandas-gbq=0.13.1=pypi_0
pandoc=2.2.3.2=0
pandocfilters=1.4.2=py37_1
param=1.9.3=py_0
parso=0.6.2=py_0
pathspec=0.7.0=py_0
pcre=8.43=he6710b0_0
pexpect=4.8.0=py37_0
pickleshare=0.7.5=py37_0
pillow=7.0.0=py37hb39fc2d_0
pip=20.0.2=py37_1
pip-tools=4.5.1=pypi_0
poyo=0.5.0=pypi_0
prometheus_client=0.7.1=py_0
prompt_toolkit=3.0.3=py_0
protobuf=3.11.4=py37he6710b0_0
ptyprocess=0.6.0=py37_0
py-xgboost=0.90=py37he6710b0_1
pyarrow=0.16.0=pypi_0
pyasn1=0.4.8=py_0
pyasn1-modules=0.2.7=py_0
pycodestyle=2.5.0=py37_0
pycparser=2.20=py_0
pyct=0.4.6=py37_0
pydata-google-auth=0.3.0=pypi_0
pyflakes=2.1.1=py37_0
pygments=2.6.1=py_0
pyjwt=1.7.1=py37_0
pyopenssl=19.1.0=py37_0
pyparsing=2.4.6=py_0
pyqt=5.9.2=py37h05f1152_2
pyrsistent=0.15.7=py37h7b6447c_0
pysal=1.14.4.post1=py37_1
pysocks=1.7.1=py37_0
python=3.7.6=h0371630_2
python-dateutil=2.8.1=py_0
python-json-logger=0.1.11=pypi_0
python_abi=3.7=1_cp37m
pytz=2019.3=py_0
pyviz_comms=0.7.3=py_0
pyyaml=5.3=py37h7b6447c_0
pyzmq=18.1.1=py37he6710b0_0
qt=5.9.7=h5867ecd_1
readline=7.0=h7b6447c_5
regex=2020.2.20=py37h7b6447c_0
requests=2.23.0=py37_0
requests-oauthlib=1.3.0=py_0
rsa=4.0=py_0
s3fs=0.4.0=pypi_0
s3transfer=0.3.3=pypi_0
scikit-learn=0.21.3=py37hd81dba3_0
scikit-survival=0.11=pypi_0
scipy=1.4.1=py37h0b6359f_0
scs=2.1.1.2=py37h4ff444d_3
send2trash=1.5.0=py37_0
setuptools=46.0.0=py37_0
sip=4.19.8=py37hf484d3e_0
six=1.14.0=py37_0
snappy=1.1.7=hbae5bb6_3
sqlalchemy=1.3.15=py37h7b6447c_1
sqlite=3.31.1=h7b6447c_0
suitesparse=5.2.0=h9e4a6bb_0
tables=3.5.2=pypi_0
tbb=2020.0=hfd86e86_0
tensorboard=2.1.0=py3_0
tensorflow=2.1.0=gpu_py37h7a4bb67_0
tensorflow-base=2.1.0=gpu_py37h6c5654b_0
tensorflow-estimator=2.1.0=pyhd54b08b_0
tensorflow-gpu=2.1.0=h0d30ee6_0
tensorflow-hub=0.7.0=pyhe6710b0_0
tensorflow-probability=0.8.0=py_0
termcolor=1.1.0=py37_1
terminado=0.8.3=py37_0
testpath=0.4.4=py_0
thrift-cpp=0.11.0=h02b749d_3
tk=8.6.8=hbc83047_0
toml=0.10.0=py37h28b3542_0
toposort=1.5=py_3
tornado=6.0.4=py37h7b6447c_1
traitlets=4.3.3=py37_0
typed-ast=1.4.1=py37h7b6447c_0
typing_extensions=3.7.4.1=py37_0
urllib3=1.25.8=py37_0
wcwidth=0.1.8=py_0
webencodings=0.5.1=py37_1
werkzeug=1.0.0=py_0
wheel=0.34.2=py37_0
whichcraft=0.6.1=pypi_0
wrapt=1.12.1=py37h7b6447c_1
xlrd=1.2.0=py37_0
xlsxwriter=1.2.8=pypi_0
xz=5.2.4=h14c3975_4
yaml=0.1.7=had09818_2
zeromq=4.3.1=he6710b0_3
zipp=2.2.0=py_0
zlib=1.2.11=h7b6447c_3
zstd=1.3.7=h0b5b093_0
